name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04   # آخرین ورژن پشتیبانی شده

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4  # جدیدترین نسخه

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4   # ✅ بروزرسانی به v4
      with:
        name: CookieApp-debug
        path: app/build/outputs/apk/debug/app-debug.apk
