name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4   # ✅ جدید

    - name: Set up JDK 17
      uses: actions/setup-java@v4 # ✅ جدید
      with:
        distribution: temurin
        java-version: 17

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CookieApp-debug
        path: app/build/outputs/apk/debug/app-debug.apk
